#!/usr/bin/env python
# coding: utf-8

# In[116]:


import pandas as pd 
df = pd.read_csv("airpassenger.csv")


# In[119]:


df


# In[120]:



df['Month'] = pd.to_datetime(df['Month'], format='%Y-%m')


# In[121]:


df.index = df['Month']
df


# In[122]:


#print(df.head())
del df['Month']
#print(df.head())


# In[123]:


df


# In[124]:


from matplotlib import pyplot as plt
df.plot()
plt.show()


# In[125]:


df['Date'] = df.index


# In[126]:


train = df[df['Date'] < pd.to_datetime("1960-08", format='%Y-%m')]
train['train'] = train['Passengers']
train


# In[127]:


del train['Date']
del train['Passengers']
train


# In[128]:


test = df[df['Date'] >= pd.to_datetime("1960-08", format='%Y-%m')]
test['test'] = test['Passengers']
del test['Date']
del test['Passengers']
print(test)
print(test.shape)


# In[129]:


plt.plot(train, color = "black")
plt.plot(test, color = "red")
plt.title("Train/Test split for Passenger Data")
plt.ylabel("Passenger Number")
plt.xlabel('Year-Month')
plt.show()


# In[ ]:





# In[130]:


get_ipython().system('pip install pmdarima')


# In[131]:


from pmdarima.arima import auto_arima
model = auto_arima(train)


# In[132]:


forecast=model.predict(n_periods=5,index=test.index)


# In[133]:


forecast.columns=['test']
forecast


# In[134]:


#mean absolute error is the difference between the actual value and predicted value
from sklearn.metrics import mean_absolute_error
print(mean_absolute_error(test['test'], forecast))


# In[ ]:
